model:  ["GIN"]
batch_size: [32]
emb_dim: [64]
drop_out: [0.5]
num_layers: [4]
num_mlp_layers: [2]
pooling: ["mean"]
lr: [0.001]
freeze_gnn: [0]
epochs: [100]
drop_feat: [0]
lr_scheduler: ["None"]
JK: ["concat"]
max_struct_size: [6]
graph_trafo: ["CWN"]
node_broadcast: [1]